"""Pose-reaching test: reach a sequence of random reachable 6-DOF poses.

Exercises the combined `ConfigurationTask` (position + orientation solved
together). For each target the controller drives the EE to a random pose; the
target pose is shown as a red position sphere + RGB orientation triad, and the
EE pose as a green position sphere + RGB triad. When the EE triad lands on the
target triad, both position and orientation have converged.

Targets are guaranteed reachable: each is generated by sampling a random joint
configuration within limits and reading its forward-kinematics pose.

Headless (saves plot + MP4):
    python -m scripts.test_pose_targets --video --n 6

Interactive window (runs the sequence, saves on close):
    python -m scripts.test_pose_targets --gui --n 8
"""
from __future__ import annotations

import argparse
import os
import time

import numpy as np

from src.arm_tracking.sim import PandaSim, PANDA_HOME
from src.arm_tracking.tasks import TaskPriorityController

VIDEO_W, VIDEO_H = 720, 544


def sample_reachable_poses(sim, n, rng):
    """Random reachable poses via FK of random in-limit joint configs."""
    poses = []
    for _ in range(n):
        q = PANDA_HOME + rng.uniform(-0.6, 0.6, sim.n_arm)
        q = np.clip(q, sim.joint_lower + 0.1, sim.joint_upper - 0.1)
        sim.reset(q)
        pos, quat = sim.get_ee_pose()
        poses.append((pos.copy(), quat.copy()))
    sim.reset()   # back to home before control starts
    return poses


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=6, help="number of random pose targets")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--max_seconds", type=float, default=3.0, help="dwell per target (s)")
    ap.add_argument("--pos_tol", type=float, default=0.01, help="position tol (m)")
    ap.add_argument("--orn_tol_deg", type=float, default=3.0, help="orientation tol (deg)")
    ap.add_argument("--gui", action="store_true")
    ap.add_argument("--video", action="store_true")
    ap.add_argument("--outdir", default="outputs")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    rng = np.random.default_rng(args.seed)
    orn_tol = np.radians(args.orn_tol_deg)

    sim = PandaSim(gui=args.gui)
    if args.gui:
        sim.setup_gui_camera()

    targets = sample_reachable_poses(sim, args.n, rng)

    # Combined 6-DOF pose controller (ConfigurationTask). Orientation gain
    # raised to match position so both converge at a similar rate.
    ctrl = TaskPriorityController(sim, combined=True, kp_orn=4.0)

    show = args.gui or args.video
    tgt_sphere = ee_sphere = tgt_triad = ee_triad = None
    if show:
        tgt_sphere = sim.add_marker(targets[0][0], rgba=(0.9, 0.1, 0.1, 1.0), radius=0.018)
        ee_sphere = sim.add_marker(targets[0][0], rgba=(0.1, 0.9, 0.15, 1.0), radius=0.013)
        tgt_triad = sim.add_triad(*targets[0], length=0.08)
        ee_triad = sim.add_triad(*targets[0], length=0.06)

    writer = gui_log = None
    video_path = os.path.join(args.outdir, "pose_test.mp4")
    if args.video and not args.gui:
        import imageio
        writer = imageio.get_writer(video_path, fps=30, macro_block_size=16)
    elif args.video and args.gui:
        gui_log = sim.start_video_log(video_path)

    cam = dict(width=VIDEO_W, height=VIDEO_H, cam_target=(0.35, 0.0, 0.5),
               distance=1.1, yaw=55, pitch=-25, use_opengl=False)

    dt = sim.timestep
    frame_every = max(1, int((1.0 / dt) / 30))

    # logs for the summary plot
    pe_log, oe_log, switch_steps = [], [], []
    results = []
    gstep = 0

    if args.gui:
        print("GUI open — watch the EE triad converge onto each target triad. "
              "Close the window or Ctrl+C to stop.")

    try:
        for ti, (tpos, tquat) in enumerate(targets):
            if args.gui and not sim.is_connected():
                break
            switch_steps.append(gstep)
            if show:
                sim.move_marker(tgt_sphere, tpos)
                sim.move_triad(tgt_triad, tpos, tquat, length=0.08)

            reached, t_reach = False, args.max_seconds
            steps = int(args.max_seconds / dt)
            for k in range(steps):
                if args.gui and not sim.is_connected():
                    break
                t0 = time.time()
                _, pe, oe, _ = ctrl.step(tpos, target_quat=tquat)
                sim.step()
                pe_n = float(np.linalg.norm(pe))
                oe_n = float(np.linalg.norm(oe))
                pe_log.append(pe_n * 1000)       # mm
                oe_log.append(np.degrees(oe_n))  # deg
                gstep += 1

                if show and k % frame_every == 0:
                    ee_pos, ee_quat = sim.get_ee_pose()
                    sim.move_marker(ee_sphere, ee_pos)
                    sim.move_triad(ee_triad, ee_pos, ee_quat, length=0.06)
                    if writer is not None:
                        writer.append_data(sim.render(**cam))
                if args.gui:
                    time.sleep(max(0.0, dt - (time.time() - t0)))

                # record the first time both tolerances are met (don't stop —
                # let it settle for the rest of the dwell so the triads converge).
                if not reached and pe_n < args.pos_tol and oe_n < orn_tol:
                    reached, t_reach = True, k * dt

            results.append((ti, reached, pe_log[-1], oe_log[-1], t_reach))
            print(f"  target {ti}: {'REACHED' if reached else 'timeout'} "
                  f"at {t_reach:4.2f}s | final pos {pe_log[-1]:6.3f} mm | "
                  f"orn {oe_log[-1]:5.3f} deg")
    except KeyboardInterrupt:
        print("\ninterrupted — saving outputs")
    except Exception as e:
        if args.gui:
            print(f"\nwindow closed — saving outputs ({type(e).__name__})")
        else:
            if writer is not None:
                writer.close()
            raise

    n_ok = sum(1 for r in results if r[1])
    print(f"\nReached {n_ok}/{len(results)} targets "
          f"(pos<{args.pos_tol*1000:.0f}mm, orn<{args.orn_tol_deg:.0f}deg)")

    if gui_log is not None:
        sim.stop_video_log(gui_log)
        print(f"  saved video -> {video_path}  (requires system ffmpeg)")
    if writer is not None:
        writer.close()
        print(f"  saved video -> {video_path}")

    _save_plot(pe_log, oe_log, switch_steps, dt, args)
    sim.close()


def _save_plot(pe_log, oe_log, switch_steps, dt, args):
    if not pe_log:
        return
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    t = np.arange(len(pe_log)) * dt
    fig, (a1, a2) = plt.subplots(2, 1, figsize=(11, 6), sharex=True)
    a1.plot(t, pe_log, "C0"); a1.axhline(args.pos_tol * 1000, color="k", ls=":", lw=1)
    a1.set_ylabel("position err (mm)"); a1.set_yscale("log"); a1.grid(alpha=0.3)
    a1.set_title("Pose reaching: random 6-DOF targets (combined ConfigurationTask)")
    a2.plot(t, oe_log, "C1"); a2.axhline(args.orn_tol_deg, color="k", ls=":", lw=1)
    a2.set_ylabel("orientation err (deg)"); a2.set_yscale("log")
    a2.set_xlabel("t (s)"); a2.grid(alpha=0.3)
    for s in switch_steps:   # vertical line at each new target
        for ax in (a1, a2):
            ax.axvline(s * dt, color="0.7", lw=0.8)
    fig.tight_layout()
    path = os.path.join(args.outdir, "pose_test.png")
    fig.savefig(path, dpi=120)
    print(f"  saved plot  -> {path}")


if __name__ == "__main__":
    main()
